# permissions for end users to edit zwhdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: zwhdeployment-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: zwh-deployment
    app.kubernetes.io/part-of: zwh-deployment
    app.kubernetes.io/managed-by: kustomize
  name: zwhdeployment-editor-role
rules:
- apiGroups:
  - apps.zwh.com
  resources:
  - zwhdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.zwh.com
  resources:
  - zwhdeployments/status
  verbs:
  - get
