apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .ObjectMeta.Name}}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Spec.Expose.IngressDomain}}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ .ObjectMeta.Name}}
                port:
                  number: {{ .ObjectMeta.Spec.Port}}

